apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-app-deployment
  namespace: hc-app
  labels:
    app: hc-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hc-app
  template:
    metadata:
      labels:
        app: hc-app
    spec:
      containers:
      - name: hc-app
        image: ghcr.io/rhjensen79/hybrid-cloud-app:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

